ServerEvents.recipes(event => {
    event.remove({output:'create_dd:steel_sheet'})
    event.remove({output:'create_dd:tin_sheet'})
    event.remove({output:'create_dd:bronze_sheet'})
    event.remove({output:'create_dd:bronze_ingot'})
    event.remove({output:'createaddition:electrum_sheet'})
    //板
    function thermal_pressing(a, b) {
        event.recipes.create.pressing([a], b)
    }
    thermal_pressing('thermal:enderium_plate','thermal:enderium_ingot')
    thermal_pressing('thermal:lumium_plate','thermal:lumium_ingot')
    thermal_pressing('thermal:signalum_plate','thermal:signalum_ingot')
    thermal_pressing('thermal:netherite_plate','minecraft:netherite_ingot')
    thermal_pressing('thermal:rose_gold_plate','thermal:rose_gold_ingot')
    thermal_pressing('thermal:steel_plate','#forge:ingots/steel')
    thermal_pressing('thermal:constantan_plate','thermal:constantan_ingot')
    thermal_pressing('thermal:invar_plate','thermal:invar_ingot')
    thermal_pressing('thermal:electrum_plate','#forge:ingots/electrum')
    thermal_pressing('thermal:bronze_plate','#forge:ingots/bronze')
    thermal_pressing('thermal:nickel_plate','thermal:nickel_ingot')
    thermal_pressing('thermal:silver_plate','thermal:silver_ingot')
    thermal_pressing('thermal:lead_plate','#forge:ingots/lead')
    thermal_pressing('thermal:tin_plate','#forge:ingots/tin')
    thermal_pressing('thermal_extra:soul_infused_plate','thermal_extra:soul_infused_ingot')
    thermal_pressing('thermal_extra:shellite_plate','thermal_extra:shellite_ingot')
    thermal_pressing('thermal_extra:twinite_plate','thermal_extra:twinite_ingot')
    thermal_pressing('thermal_extra:dragonsteel_plate','thermal_extra:dragonsteel_ingot')
})