ServerEvents.tags('item', event => {
    event.add('kubejs:bio_fuel', 'minecraft:moss_block')
    event.add('kubejs:bio_fuel', 'minecraft:melon')
    event.add('kubejs:bio_fuel', 'minecraft:potato')
    event.add('kubejs:bio_fuel', 'minecraft:nether_wart')
    event.add('kubejs:bio_fuel', 'minecraft:cake')
    event.add('kubejs:bio_fuel', 'minecraft:pumpkin')
    event.add('kubejs:bio_fuel', 'minecraft:carrot')
    event.add('kubejs:bio_fuel', 'minecraft:brown_mushroom')
    event.add('kubejs:bio_fuel', 'minecraft:bread')
    event.add('kubejs:bio_fuel', 'minecraft:beetroot')
    event.add('kubejs:bio_fuel', 'minecraft:wheat')
    event.add('kubejs:bio_fuel', 'minecraft:shroomlight')
    event.add('kubejs:bio_fuel', 'minecraft:apple')
    event.add('kubejs:bio_fuel', 'minecraft:sunflower')
    event.add('kubejs:bio_fuel', 'minecraft:sugar_cane')
})